include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
  # Exclude vendored/flutter SDK sources and non-app code from analysis
  - flutter/**
  - .dart_tool/**
  - build/**
  # Common generated files
  - "**/*.g.dart"
  - "**/*.freezed.dart"

linter:
  # Disable all lints to eliminate the info-level noise for now. We can re-enable
  # a curated subset later without reintroducing hundreds of infos.
  rules: []