// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFsfZEk2N3w27ohrXyFWSOW2Lm6bcBybE',
    appId: '1:596436988958:web:0713d48838f3a0349e6a0f',
    messagingSenderId: '596436988958',
    projectId: 'v29bvc2fec6tbbyy7j9h4tddz1dq28',
    authDomain: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebaseapp.com',
    databaseURL: 'https://v29bvc2fec6tbbyy7j9h4tddz1dq28-default-rtdb.firebaseio.com',
    storageBucket: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZaIYwU5M7uIVTbFWqFp_vGa-VYFz4ak',
    appId: '1:596436988958:android:e5a7c74a7c5b7a9e6a0f',
    messagingSenderId: '596436988958',
    projectId: 'v29bvc2fec6tbbyy7j9h4tddz1dq28',
    databaseURL: 'https://v29bvc2fec6tbbyy7j9h4tddz1dq28-default-rtdb.firebaseio.com',
    storageBucket: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGxe_YcFtaehqE_Kl2d9J5UwXsQbJbF2c',
    appId: '1:596436988958:ios:c8a2d9f5b4e3a6c19e6a0f',
    messagingSenderId: '596436988958',
    projectId: 'v29bvc2fec6tbbyy7j9h4tddz1dq28',
    databaseURL: 'https://v29bvc2fec6tbbyy7j9h4tddz1dq28-default-rtdb.firebaseio.com',
    storageBucket: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebasestorage.app',
    iosBundleId: 'com.example.colorCanvas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGxe_YcFtaehqE_Kl2d9J5UwXsQbJbF2c',
    appId: '1:596436988958:ios:c8a2d9f5b4e3a6c19e6a0f',
    messagingSenderId: '596436988958',
    projectId: 'v29bvc2fec6tbbyy7j9h4tddz1dq28',
    databaseURL: 'https://v29bvc2fec6tbbyy7j9h4tddz1dq28-default-rtdb.firebaseio.com',
    storageBucket: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebasestorage.app',
    iosBundleId: 'com.example.colorCanvas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFsfZEk2N3w27ohrXyFWSOW2Lm6bcBybE',
    appId: '1:596436988958:web:0713d48838f3a0349e6a0f',
    messagingSenderId: '596436988958',
    projectId: 'v29bvc2fec6tbbyy7j9h4tddz1dq28',
    authDomain: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebaseapp.com',
    databaseURL: 'https://v29bvc2fec6tbbyy7j9h4tddz1dq28-default-rtdb.firebaseio.com',
    storageBucket: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCFsfZEk2N3w27ohrXyFWSOW2Lm6bcBybE',
    appId: '1:596436988958:web:0713d48838f3a0349e6a0f',
    messagingSenderId: '596436988958',
    projectId: 'v29bvc2fec6tbbyy7j9h4tddz1dq28',
    authDomain: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebaseapp.com',
    databaseURL: 'https://v29bvc2fec6tbbyy7j9h4tddz1dq28-default-rtdb.firebaseio.com',
    storageBucket: 'v29bvc2fec6tbbyy7j9h4tddz1dq28.firebasestorage.app',
  );

}